- name: "install storpool.conf"
  copy:
    src: "{{ sp_config }}"
    dest: /etc/

- name: "download getpackage.py"
  get_url:
    url: https://vault.storpool.com/getpackage.py
    dest: "{{ sp_toolsdir }}"
    mode: '0755'
  when: sp_release_file == 'web'

- name: "download StorPool package (release: {{ sp_release }})"
  shell: "{{ sp_toolsdir }}/getpackage.py -g {{ sp_release }}"
  register: sp_release_tgz
  when: sp_release_file == 'web'

- name: "generate-build-conf"
  run_once: true
  become: no
  local_action: command chdir="{{ sp_custdir }}/{{ sp_cluster }}" /usr/local/bin/generate-build-conf
  when: sp_release_file == 'poli'

- name: "copytoservers"
  run_once: false
  become: no
  local_action: command chdir="{{ sp_custdir }}/{{ sp_cluster }}" /usr/local/bin/copytoservers-old r={{ sp_release }} host={{ inventory_hostname }}
  when: sp_release_file == 'poli'

- name: "copy local release file to nodes"
  copy:
    src: "{{ sp_release_file }}"
    dest: "{{ sp_toolsdir }}"
  when: sp_release_file not in [ 'web', 'poli' ]

- name: "prepare copied release file for extraction"
  set_fact:
    sp_release_tgz: { stdout: "{{ sp_release_file | basename }}" }
  when: sp_release_file not in [ 'web', 'poli' ]

- name: "unpack release file"
  unarchive:
    src: "{{ sp_toolsdir }}/{{ sp_release_tgz.stdout | basename }}"
    dest: "{{ sp_toolsdir }}"
    remote_src: yes
  when: sp_release_file != 'poli'

- name: "get unpacked StorPool release directory"
  shell: 'ls -d {{ sp_toolsdir }}/storpool-1[89].0*/ | sort -V | tail -n 1'
  register: sp_install_dir

- name: "StorPool install"
  shell: "common/usr/lib/storpool/install_modules_helper -w {{ sp_toolsdir }} -m '{{ sp_install_services }}'"
  args:
    chdir: "{{ sp_install_dir.stdout }}"
