- name: "restart rsyslog"
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes

- name: "reload sysctl entries"
  shell: '`which sysctl` --system'

- name: "increase crashkernel size on Ubuntu"
  shell: 'echo "GRUB_CMDLINE_LINUX_DEFAULT=\"\$GRUB_CMDLINE_LINUX_DEFAULT crashkernel=512M"\" > /etc/default/grub.d/kdump-tools.cfg'
  when: ansible_distribution == 'Ubuntu'

- name: "run patchkdumptools on Ubuntu"
  shell: '/usr/lib/storpool/patchkdumptools'
  when: ansible_distribution == 'Ubuntu'


- name: "check if booting via EFI on RHEL/CentOS"
  stat:
    path: /boot/efi/EFI/centos/grub.cfg
  register: sp_centos_efi
  when: ansible_os_family == 'RedHat'

- name: "update GRUB on CentOS/RHEL"
  shell: "/usr/sbin/grub2-mkconfig -o {{ '/boot/efi/EFI/centos/grub.cfg' if sp_centos_efi.stat.exists else '$(readlink -f /etc/grub2.cfg)' }}"
  when: ansible_os_family == 'RedHat'

- name: "update GRUB on Ubuntu/Debian"
  shell: "update-grub2"
  when: ansible_os_family == 'Debian'
