- import_tasks: 00_variables.yml
  any_errors_fatal: true
  tags: test
- import_tasks: 05_dependencies.yml
- import_tasks: 06_tuning.yml
- import_tasks: 07_directories.yml
- import_tasks: 08_test_memory.yml
  when: not sp_vm
  tags: test
- import_tasks: 18_sp_support_common.yml
  when: sp_poli
- import_tasks: 20_install_storpool.yml
- import_tasks: 21_post_install.yml
- import_tasks: 25_check_node_in_conf.yml
- import_tasks: 30_configure_network.yml
  when: sp_configure_network
- import_tasks: 35_init_drives.yml
  when: sp_roles.server
- import_tasks: 40_cgroups.yml
- import_tasks: 45_vf_genconf.yml
  when: not sp_vm
- import_tasks: 50_start_services.yml
