galaxy_info:
  author: Kaloyan Kotlarski
  namespace: storpool
  role_name: configure_node
  description: Ansible role for setup, configuration and validation of StorPool networking
  company: StorPool Storage AD
  license: Apache-2.0
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
  min_ansible_version: 2.12
  galaxy_tags: []
