---
- name: Copy drives init tools
  copy:
    src: "init_drive.sh"
    dest: "{{ sp_toolsdir }}"
    mode: 0755
  when: not sp_testing_lab

- name: Init drives for testing lab env
  command: >
    /usr/local/bin/initdisks
  changed_when: false
  when: sp_testing_lab

- name: Init drives
  command: >
    {{ sp_init_drive }} {{ item }} {{ sp_diskid_prefix }}
    {{ sp_init_node if sp_new_cluster else 'noinit' }}
  changed_when: false
  when: not sp_testing_lab
  with_items: "{{ sp_drives }}"

- name: Get needed number of server instances
  script: get_instances.py
  args:
    executable: "{{ sp_python_executable }}"
  changed_when: false
  register: sp_instances

- name: Stop server instances
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  changed_when: false
  with_items: "{{ sp_instances.stdout_lines }}"

- name: Stop storpool_nvmed
  ansible.builtin.service:
    name: storpool_nvmed
    state: stopped
    enabled: no
  changed_when: false
  when:
    - sp_roles.nvme

- name: Expose all NVMe drives
  command: "{{ sp_expose_nvme_drives }}"
  changed_when: false
  ignore_errors: yes
  when:
    - sp_roles.nvme

- name: Settle udev
  command: udevadm settle
  changed_when: false

- name: Assign drives to servers
  shell: |
    {{ sp_multi_server_helper }} -i {{ sp_server_instances }} \
    | bash
  changed_when: false
  args:
    executable: /bin/bash
  when: sp_multi_server_helper_enabled
  tags:
    - skip_ansible_lint
