---
- name: Install (StorPool Support Tools)
  delegate_to: localhost
  run_once: false
  become: false
  command:
    chdir: "{{ sp_custdir }}/{{ sp_cluster }}"
    cmd: "{{ sp_installtools }} {{ inventory_hostname }}"
  changed_when: false
  when:
    - sp_cluster is defined

- name: Check if mlc exists (StorPool Support Tools)
  stat:
    path: "{{ sp_mlc }}"
  register: mlc_present
  when:
    - sp_vm is defined and
      not sp_vm | bool

- name: Perform mlc test (StorPool Support Tools)
  shell: >
    [[ ! -d "/tmp/mlc/" ]] && mkdir -p /tmp/mlc/; \
    [[ ! -f "/tmp/mlc/mlc.output" ]] && {{ sp_toolsdir }}/mlc/mlc > /tmp/mlc/mlc.output || /bin/true
  changed_when: false
  args:
    executable: /bin/bash
  when:
    - sp_vm is defined and
      not sp_vm | bool and
      mlc_present.stat is defined and
      mlc_present.stat.exists
  tags:
    - skip_ansible_lint

- name: Collect inventory (StorPool Support Tools)
  delegate_to: localhost
  run_once: false
  become: false
  command:
    chdir: "{{ sp_custdir }}/{{ sp_cluster }}"
    cmd: "{{ sp_collect_inventory }} {{ inventory_hostname }}"
  changed_when: false
