---
- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
    enabled: yes
  changed_when: false

- name: Reload sysctl entries
  shell: |
    `which sysctl` --system
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Include distro-specific tasks
  include_tasks: "subtasks/post_install_{{ ansible_os_family|lower }}.yml"

- name: Test Memory - check on async task
  async_status:
    jid: "{{ memory_test_sleeper.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 200
  delay: 30
  when:
    - sp_vm is defined and
      not sp_vm | bool and
      memory_test_sleeper is defined and
      memory_test_sleeper.ansible_job_id is defined

- name: Make sure the node exists in storpool.conf
  shell: '[ -n "$(storpool_showconf -n -e SP_OURID)" ]'
  changed_when: false
  tags:
    - skip_ansible_lint
