---
# tasks file for configure_cgroups
- name: Checking if StorPool cgroup configuration exists
  become: true
  stat:
    path: /etc/cgconfig.d/storpool.slice.conf
  register: sp_slice_conf_file

- name: Checking if the kernel has memory swap cgroup enabled
  stat:
    path: /sys/fs/cgroup/memory/memory.memsw.usage_in_bytes
  register: cgroup_memsw_file

- name: Setting set_memsw fact
  set_fact:
    sp_cg_set_memsw: '{{ "1" if cgroup_memsw_file.stat.exists else "0" }}'
    cacheable: true

- name: Dumping sp_cg_conf_extra value
  debug:
    var: sp_cg_conf_extra
    verbosity: 2

- name: Generating cgroup configuration files
  become: true
  command:
    cmd: >-
      {{ sp_cgtool_bin }}
      conf
      converged={{ "1" if sp_cg_hyperconverged else "0" }}
      {% if sp_cg_conf_extra | length > 0 %}
      {{ sp_cg_conf_extra }}
      {% endif %}
      SET_MEMSW={{ sp_cg_set_memsw }}
  when: not sp_slice_conf_file.stat.exists
  notify: 'start cgconfig'

- name: Migrating cgroup configuration
  become: true
  command:
    cmd: >-
      {{ sp_cgtool_bin }}
      conf -M -E
      converged={{ "1" if sp_cg_hyperconverged else "0" }}
      {% if sp_cg_conf_extra | length > 0 %}
      {{ sp_cg_conf_extra }}
      {% endif %}
      SET_MEMSW={{ sp_cg_set_memsw }}
  when: sp_slice_conf_file.stat.exists
